import {
  DB_CONNECTION_TIMEOUT,
  DB_CONSTRAINT_VIOLATION,
  FOREIGN_KEY_CONSTRAINT_VIOLATION,
  INTERNAL_SERVER_ERROR,
  REQUIRED_RECORDS_NOT_FOUND,
  UNIQUE_CONSTRAINT_VIOLATION,
} from './error-messages.js';

export type PrismaDerivedError =
  | typeof UNIQUE_CONSTRAINT_VIOLATION
  | typeof FOREIGN_KEY_CONSTRAINT_VIOLATION
  | typeof DB_CONSTRAINT_VIOLATION
  | typeof DB_CONNECTION_TIMEOUT
  | typeof REQUIRED_RECORDS_NOT_FOUND
  | typeof INTERNAL_SERVER_ERROR;
