name: CI

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      NX_NO_CLOUD: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npx prisma generate --schema api-gateway/prisma/schema.prisma
      - run: npx prisma migrate deploy --schema api-gateway/prisma/schema.prisma

      - run: npx nx format:check --base="remotes/origin/main"
      - run: npx nx run-many -t lint test build typecheck --all

      - run: npx playwright install --with-deps
      - run: npx nx e2e api-gateway-e2e
      - run: npx nx e2e web-e2e
